(define (make-segment a b c d)
  (cons (make-point a b) (make-point c d)))
(define (start-segment l) (car l))
(define (end-segment l) (cdr l))
(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define (midpoint-segment l)
  (cons (/ (+ (x-point (start-segment l))
  	      (x-point (end-segment l)))
	    2)
	(/ (+ (y-point (start-segment l))
	      (y-point (end-segment l)))
	    2)))

